### ISSUE TITLE
Verificar a sintaxe do Ultrassom.

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/Brasilino#1]
Ultrassom implementado baseado na biblioteca: https://github.com/JRodrigoTech/Ultrasonic-HC-SR04, Porém pode ter ficado ainda complicado e ter como melhorar. Removi algumas coisas que não teriam necessidade, mas ainda tem coisa de mais, o ideal talvez seja ficar algo apenas como ultrassom(); e pronto.

**Comment by ErickSimoes** [comment]
Poderia ser interessante usar essa outra lib, a [Ultrasonick](https://github.com/ErickSimoes/Ultrasonick) por exemplo?
