### ISSUE TITLE
Definir e usar cabeçalho em todos os arquivos de código

### ISSUE THREAD

**Issue by ErickSimoes** [OtacilioN/Brasilino#15]
O cabeçalho deve seguir um padrão como esse:
```c++
/*
 * Ultrasonic.h
 * 
 * Library for HC-SR04 Ultrasonic Ranging Module in a minimalist way
 *
 * created 3 Apr 2014
 * by Erick Simões (github: @ErickSimoes | twitter: @AloErickSimoes)
 * modified 23 Jan 2017
 * by Erick Simões (github: @ErickSimoes | twitter: @AloErickSimoes)
 * 
 * Released into the MIT License.
 */
```

E deve ser aplicado em todos os arquivos de código (`.h` e `.cpp`)

**Comment by OtacilioN** [comment]
Por mim poderia seguir esse padrão:

/*
 * Brasilino.h
 * 
 * Biblioteca de tradução e facilitação de funções para Arduino em PT-BR
 *
 * Criado em 7 Julho 2016
 * Por Otacilio Neto (github: @OtacilioN | Email: contato@otacilio.me), Thiago Augusto (github: ThiagoAugustoSM | Email: martinsthiagoaugusto@gmail.com)
 * Modificado em 24 Fevereiro 2017
 * Por Erick Simões (github: @ErickSimoes | twitter: @AloErickSimoes)
 * 
 * Publicado na Licença GPL-3.0
 */
