### ISSUE TITLE
Dentro do código há o uso de tipos nativos e traduzidos

### ISSUE THREAD

**Issue by ErickSimoes** [OtacilioN/Brasilino#17]
Não há consistência entre o uso de tipos nativos e palavras reservadas (int, float, void...) e suas traduções (inteiro, decimal, vazio) dentro do código.

**Comment by OtacilioN** [comment]
De fato, um padrão precisa ser adotado, porém, seria melhor utilizar o padrão já da Brasilino no CPP? Para incentivar que quem já programa em Brasilino possa modificar a biblioteca.

**Comment by ErickSimoes** [comment]
Imaginando que haverá extensões da Brasilino no futuro, adotar código nativo na implementação de funções da biblioteca provê melhor suporte a essas futuras implementações.
Assim, a interface (`.h`) é responsável por traduzir o código nativo e abstrair código mais complexo e de outras bibliotecas.
