### ISSUE TITLE
Revisar/melhorar documentação dos comandos

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/Brasilino#27]
Foi percebido que alguns comandos não estão abrangidos pela documentação, bem como talvez a melhor maneira não seja ter a tabela inteira de comandos no READ.me, creio que esta seja a hora de iniciarmos a WIKI

**Comment by ErickSimoes** [comment]
Estou completamente de acordo!
Podemos marcar um mutirão para fazermos a Wiki, tanto com a documentação "técnica", explicando os comandos e mostrando seus equivalentes, como também exercícios e atividades didáticas, pensando no uso por estudantes e professores.

**Comment by felipebastosweb** [comment]
Pq não deixam o readme e complementam com uma pasta docs tendo outros arquivos em markdown. O usuário leigo não conhece nem tem acesso ao Wiki .. já uma docs o acompanharia em qqer lugar

**Comment by OtacilioN** [comment]
Boa ideia @felipebastosweb

**Comment by pedroguilhermelima** [comment]
Podemos listar todas os comandoas na issues, o que vocês acham? Seria fácil documentar e adicionar coisas que depois seriam colocadas no ReadMe de modo fácil.

**Comment by pedroguilhermelima** [comment]
Estou fazendo isso ^^ Concluir a Wiki
