### ISSUE TITLE
definição de void

### ISSUE THREAD

**Issue by alessonrenato** [OtacilioN/Brasilino#4]
``` 
#define nulo void
```
Nulo não seria NULL/NIL? Void tá mais pra vazio.
```
#define funcao void
```
Nesse caso o mais adequado é "procedimento"

Minha sugestão:
```
#define vazio void
#define procedimento void
#define nulo NULL
```

**Comment by OtacilioN** [comment]
Implementado! Obrigado pela sugestão!
