### ISSUE TITLE
Então, fiz a Wiki. ^^

### ISSUE THREAD

**Issue by ghost** [OtacilioN/Brasilino#46]
Então, fiz a Wiki. https://github.com/kwekwwelkwelk/Brasilino/wiki **^^**

**Comment by OtacilioN** [comment]
Ficou muito boa a Wiki @pglapds, parabéns! Como podemos adicionar-la ao repositório original? É possível fazer um pull request com a wiki?

**Comment by kwekwwelkwelk** [comment]
> Muiro obrigado pela sua contribuição @pglapds,
> 
> Ficou excelente, adorei o modelo do Wiki!
> 
> Como podemos adicioná-la ao repositório original? É possível fazer isso através de pull request?

Ys.
