### ISSUE TITLE
Tradução do termo "Unsigned"

### ISSUE THREAD

**Issue by r4faelrs** [OtacilioN/Brasilino#49]
A tradução do termo "unsigned" foi atribuída ao termo "modulo" em PT, fiquei confuso ao ler, e após discutir com alguns colegas a respeito, penso que essa tradução pode causar conflito, pois já existe uma função que dá o valor absoluto de uma variável (abs()), e pela tradução "modulo" o usuário iniciante pode confundir e pensar que são equivalentes.

Sugiro que tal tradução seja revista, "positivo" talvez seja uma saída, ou até mesmo definir "tipo_positivo" para cada tipo de dado que suporta "unsigned".

**Comment by OtacilioN** [comment]
Opa @r4faelrs muito obrigado pela sugestão, de fato faz todo sentido.

O @ViniciosSilva811 abriu um pull request adicionando isso a lib, que hoje foi mergeado e aprovado e já estará disponível na biblioteca na próxima versão que deve sair até o fim desse mês.

Caso você queira adicionar seu nome ao código é bem vindo a abrir um pull request no comentário da linha colocando:

#define positivo unsigned // Contribuição de @viniciossilva811 e @r4faelrs através de issue

Muito obrigado.
