### ISSUE TITLE
Verificar funcionamento do USAR_BAUD

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/Brasilino#5]
Realizei um teste e não estava funcionando, marcando para verificar posteriormente.

**Comment by OtacilioN** [comment]
Resolvido com a criação da função inciarSerialBaud

**Comment by ErickSimoes** [comment]
A fim de se obter uma maior usabilidade, esta issue será reaberta até que a questão de usabilidade seja solucionada.
