### ISSUE TITLE
Tradução de "#include" e "#define"

### ISSUE THREAD

**Issue by ViniciosSilva811** [OtacilioN/Brasilino#56]
Olá, é possível traduzir o termo "#include" para "#incluir" (ou "#importar") e "#define" para "#definir"?

**Comment by OtacilioN** [comment]
Infelizmente da forma que a lib é estruturada hoje não encontramos uma maneira de fazer isso =/

Meu sonho era que a primeira linha da biblioteca fosse

>#define definir define
