### ISSUE TITLE
Usar Arduino-cli como Actions para compilar para múltiplas plataformas

### ISSUE THREAD

**Issue by SteffanoP** [OtacilioN/Brasilino#66]
## Requisição de Recursos

A ideia é implantar a Action oficial da [Arduino CLI](https://github.com/arduino/setup-arduino-cli) para compilar códigos de exemplos para múltiplas plataformas, visto que, fica mais fácil no processo de triagem de testes das plataformas, como das dificuldades em #26

## Vantagens

Possibilita realizar uma triagem mais detalhada nas compilações de códigos para diversas plataformas Arduino (ex.: arduinoavr, arduinoOTA, esp32, esp8266 e etc.).

## Documentação de como fazer

https://blog.arduino.cc/2019/11/14/arduino-on-github-actions/
https://github.com/arduino/setup-arduino-cli

**Comment by SteffanoP** [comment]
Posso ficar responsável por isso, mas gostaria de saber da comunidade se seria realmente útil ao projeto e em quais códigos e plataformas deveria ser realizada a Action de Compile.

**Comment by ErickSimoes** [comment]
Muito massa @SteffanoP!

Na PR #64 foi implementado o Arduino Lint, então vai ser ótimo ter o Arduino CLI rodando também.

Imagino que em um primeiro momento, podemos focar nas placas do Arduino Uno, Mega, Leonardo e algum compatível com o ATtiny85 (do Franzininho).

**Comment by SteffanoP** [comment]
@ErickSimoes Quanto ao Franzininho, dei uma olha rapidamente e vi que ele é semelhante ao Arduino Gemma, você acha que poderíamos utilizar o compilador do Arduino Gemma?

Há também a possibilidade de utilizar a Arduino-CLI para placas externas ao ecossistema oficial Arduino (Arduino AVR)... Pode ser que seja interessante também inserir o compilador do Micronucleus.

**Comment by ErickSimoes** [comment]
@SteffanoP, ótimo usar o Gemma!

Nunca usei o Micronucleus, mas me parece interessante adotar.

Você também comentou sobre a possibilidade de compilar para outras plataformas, tais como ESP. Eu não tenho mapeado o uso da Brasilino em outras plataformas (inclusive, seria uma coisa boa da gente tentar descobrir né @OtacilioN?), mas sabemos que isso é uma possibilidade. Se você considerar viável, poderia ser adicionado ao menos o ESP8266, que compõe o NodeMCU.

**Comment by SteffanoP** [comment]
> Nunca usei o Micronucleus, mas me parece interessante adotar.

Anotado! Vou trabalhar encima para adicionar a plataforma.

> Você também comentou sobre a possibilidade de compilar para outras plataformas, tais como ESP. Eu não tenho mapeado o uso da Brasilino em outras plataformas (inclusive, seria uma coisa boa da gente tentar descobrir né @OtacilioN?), mas sabemos que isso é uma possibilidade. Se você considerar viável, poderia ser adicionado ao menos o ESP8266, que compõe o NodeMCU.

Daqui eu já não acho interessante, porque eu creio que a política atual só envolve essas placas que nós comentamos (Arduino AVR e Variantes ATtiny85). Acho que seria mais interessante implementar novas plataformas na CI, como ESP (incluindo ESP8266), quando o repo Brasilino oferecer suporte para tal, **como um todo**; pois pode ser que para algumas implementações não seja compatível com a plataforma ESP, devido a robustez da mesma, e daí apresentar erros indesejados enquanto a biblioteca estiver focada na plataforma Arduino AVR.

**Comment by ErickSimoes** [comment]
Entendi e estou de acordo 👍

**Comment by OtacilioN** [comment]
Opa, excelente ideia @SteffanoP obrigado por contribuir com a Brasilino, irei revisar o MR ainda hoje.
