### ISSUE TITLE
Criar um arquivo de testes

### ISSUE THREAD

**Issue by ErickSimoes** [OtacilioN/Brasilino#7]
Criar um `.ino` que execute todos os comandos do **Brasilino**.
Ele deve funcionar como um _teste unitário_.
Deve ser executado sempre que uma modificação for feita, para garantir que tudo continua funcionando.

**Comment by OtacilioN** [comment]
Creio que vou trabalhar nisso ainda hoje!

**Comment by OtacilioN** [comment]
@ErickSimoes este arquivo poderia se chamar quarentaedois.ino? Já que ele seria a resposta pra a Brasilino e tudo mais? Ou melhor não usar esse EasterEgg objetivando mais? Com o nome tudo.ino ou algo do tipo?

**Comment by ErickSimoes** [comment]
Me gusta EasterEggs 👍

**Comment by ErickSimoes** [comment]
Qual o andamento desse arquivo de testes @OtacilioN?

**Comment by OtacilioN** [comment]
Durante a semana toda quase não fiz nada nele por falta de internet, mexi um pouco antes de ontem, mas devo adiantá-lo ou terminá-lo hoje. Seria interessante ter a Brasilino aprovada antes do Arduino Day.

**Comment by ErickSimoes** [comment]
Seria ótimo sim, vamos correr pra adiantar isso então.

**Comment by OtacilioN** [comment]
Prontos pro release 1.0.0 ?

**Comment by ErickSimoes** [comment]
Sim 👍
