### ISSUE TITLE
Essa biblioteca ainda existe?

### ISSUE THREAD

**Issue by rgodoy86** [OtacilioN/Brasilino#75]
Olá pessoal, achei essa ideia maravilhosa! Gostaria de saber se essa biblioteca ainda é utilizada.

Raphael

**Comment by ErickSimoes** [comment]
Oi @rgodoy86, sim, sim.

A biblioteca ainda está disponível diretamente para ser acessada pela IDE do Arduino ou baixando manualmente aqui pelo GitHub.

**Comment by rgodoy86** [comment]
Muito obrigado!
