### ISSUE TITLE
Escrever no README instruções sobre como usar o Brasilino

### ISSUE THREAD

**Issue by ErickSimoes** [OtacilioN/Brasilino#8]
Objetivo e todos os métodos devem ser descritos no `README`.
Se forem muitos, pode-se considerar fazer uma **Wiki**.

**Comment by OtacilioN** [comment]
README.md feito! Porém algumas funções ainda não estão documentadas, e por serem bastante faz-se necessário a criação do Wiki de fato!

**Comment by pedroguilhermelima** [comment]
> README.md feito! Porém algumas funções ainda não estão documentadas, e por serem bastante faz-se necessário a criação do Wiki de fato (issue: #11)!

Quais funções? Estou criando a Wiki ^^  Estou criando o sumário: 1- Palavras-chaves. 2- Apresentação Brasilino. 3- Biblioteca .h, .cpp.  +- assim, por enquanto.
